# Generated by Django 5.0 on 2026-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', '💳 Банковская карта'), ('sbp', '🏦 СБП (Система быстрых платежей)'), ('tinkoff', '💜 Tinkoff'), ('sber', '🟢 СберБанк'), ('yoomoney', '💰 ЮMoney'), ('cash', '💵 Наличные при получении')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ В обработке'), ('confirmed', '✅ Подтверждён'), ('shipped', '📦 Отправлен'), ('delivered', '🏠 Доставлен'), ('delayed', '⚠️ Задерживается'), ('cancelled', '❌ Отменён')], default='pending', max_length=20),
        ),
    ]
