# Generated by Django 5.0 on 2026-05-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_lower',
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
    ]
