# Generated by Django 5.0 on 2026-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя автора'),
        ),
    ]
