# Generated by Django 5.0 on 2026-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_composition_product_discount_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', '💳 Банковская карта'), ('sbp', '🏦 СБП (Система быстрых платежей)'), ('t-bank', '💜 T-Банк'), ('sber', '🟢 СберБанк'), ('cash', '💵 Наличные при получении')], default='card', max_length=20),
        ),
    ]
